//
//  Tests.c
//  hadrons EOS
//
//  Created by Clebson Graeff on 2016-08-16.
//  Copyright © 2016 Clebson Graeff. All rights reserved.
//

#include <stdbool.h>
#include <strings.h>
#include <stdio.h>
#include <math.h>

#include "CommandlineOptions.h"
#include "Tests.h"
#include "AuxiliaryFunctions.h"
#include "ZeroTemperatureEOS.h"
#include "Constants.h"
#include "Parameters.h"

/*
 * RunTests(): A place to run tests.
 *
 *  Purpose:
 *  Running tests is always a good idea, but they tend to clutter
 *  the code. To keep things a bit more neat, all tests should
 *  be put in this function.
 *
 *  Any function may be called from here, as long as the header that
 *  contains the function prototype is included with
 *      #include "the_header.h"
 *  That, however, will exclude functions that are declared in 'main.c'
 *  as that file has no corresponding header. This will exclude the loop
 *  on the run variable and the main products of the calculation. Those
 *  results should be tested by other means (that is, not in this program).
 *
 *  Template:
 *  The tests should be written as follows:
 *  RunTests()
 *  {
 *      #pragma mark Thermodynamic potential as function of mass (1)
 *      //
 *      // Description (2)
 *      //
 *      if (true) (3)
 *      {
 *          printf("Thermodynamic potential as function of mass\n"); (4)
 *
 *          // Set path for and create log file
 *          SetFilePath("tests/zeroed-gap-equation/"); (5)
 *          FILE * log_file = OpenFile("run.log");
 *
 *          // Set path for other files
 *          SetFilePath("tests/zeroed-gap-equation/data/"); (6)
 *
 *          SetParametersSet("eNJL1"); (7)
 *
 *          // do stuff (8)
 *
 *          fclose(log_file); (9)
 *
 *          UnsetFilePath(); (10)
 *      }
 *  }
 *  where
 *       (1) Some editor (e.g. Xcode, TextWrangler) make a list of functions
 *           contained in a file. Any '#pragma mark A Title' is listed in that
 *           list as 'A Title'. This makes the navigation through the tests
 *           easier.
 *       (2) A nice description of the purpose of the test is always a good
 *           idea.
 *       (3) The 'if' makes enabling/disabling the test really simple, it's just
 *           a matter of setting the argument of the 'if' to true/false. Also,
 *           the variables declared inside the {} block exist only inside the
 *           block. This prevent the unintended reuse of meaningless values from
 *           other tests.
 *       (4) Output the test being run to the screen. This should be the same
 *           text as the 'A Title' in the '#pragma mark'.
 *       (5) Set the path to a directory specific to the current test and
 *           create a log file. Any information of the test may be saved in
 *           that log.
 *       (6) Set the path to other files generated by the test.
 *       (7) Chooses a parameters set to run the current test.
 *       (8) The test itself should be coded at that point.
 *       (9) Close log file.
 *      (10) Unset the files path. (This is necessary as other parts of the code
 *           may expect it to be the default, which is the dir that contais the
 *           executable file.)
 *
 */

void RunTests()
{
#pragma mark Zeroed Gap Equation
    
    // Write the zeroed gap equation for a set of proton and neutron
    // densities, for the eNJL1 parameters set. This serves for
    // verification purposes, as we should get a characteristic
    // curve. This tests functions used in the zero temperature case.
	if (true)
	{
        printf("\tZeroed Gap Equation\n");
        
        // Set path for and create log file
        SetFilePath("tests/zeroed-gap-equation/");
        FILE * log_file = OpenFile("run.log");
        
        // Set path for other files
        SetFilePath("tests/zeroed-gap-equation/data/");

        SetParametersSet("eNJL1");
        
        double neutron_density[9] = {0.0125, 0.025, 0.0375, 0.05, 0.0625, 0.075, 0.0875, 0.1, 0.1125};
        double proton_density[9] = {0.0125, 0.025, 0.0375, 0.05, 0.0625, 0.075, 0.0875, 0.1, 0.1125};
        
        double neutron_fermi_momentum[9];
        double proton_fermi_momentum[9];
        
        for (int i = 0; i < 9; i++){
            neutron_fermi_momentum[i] = FermiMomentum(neutron_density[i]);
            proton_fermi_momentum[i] = FermiMomentum(proton_density[i]);
        }
		
        for (int i = 0; i < 9; i++){
            for (int j = 0; j < 9; j++){
            
                double m = 0;
                
                char filename[256];
                sprintf(filename, "gap_dens_%d_%d.dat", i, j);
                
                FILE * f = OpenFile(filename);
                
                gap_equation_input input;
                input.proton_density = proton_density[i];
                input.neutron_density = neutron_density[j];
                input.proton_fermi_momentum = proton_fermi_momentum[i];
                input.neutron_fermi_momentum = neutron_fermi_momentum[j];
                
                while (m < 1000.0) {
                    fprintf(f, "%20.15E\t%20.15E\n", m, GapEquation(m, &input));
                    m += 0.5;
                }
                
                fclose(f);
            }
        }

        fprintf(log_file, "Write the zeroed gap equation for a set of proton and neutron\n"
                          "densities, for the eNJL1 parameters set. This serves for\n"
                          "verification purposes, as we should get a characteristic\n"
                          "curve. This tests functions used in the zero temperature case.\n\n");
        fprintf(log_file, "The following values of densities (and corresponding Fermi momenta)\n"
                          "were used:\n");
        fprintf(log_file, "neutron_density = {0.0125, 0.025, 0.0375, 0.05, 0.0625, 0.075, 0.0875, 0.1, 0.1125};\n"
                          "proton_density = {0.0125, 0.025, 0.0375, 0.05, 0.0625, 0.075, 0.0875, 0.1, 0.1125};\n");
        
        PrintParametersToFile(log_file);
        
		fclose(log_file);
        
        UnsetFilePath();
	}
           
#pragma mark Thermodynamic potential as function of mass
    //
    // Writes the thermodynamic potential as a function
    // of mass. In particular, we are interested in seeing
    // that the minimum value is obtained at mass = nucleon mass.
    // (This is valid for zero temperature and chemical potential
    // [chemical potential == 0 -> barionic density == 0])
    //
    if (true)
    {
        printf("Thermodynamic potential as function of mass\n");
        // Set path for and create log file
        SetFilePath("tests/zeroed-gap-equation/");
        FILE * log_file = OpenFile("run.log");
        
        // Set path for other files
        SetFilePath("tests/zeroed-gap-equation/data/");
        
        SetParametersSet("eNJL1");
        
        int points_number = 1000;

        double mass_min = 0.1;      // (MeV)
        double mass_max = 3.0E3;    // (MeV)

        double proton_fraction = 0.5;
        double barionic_density = 0.15; // (MeV) // Should be zero

        gsl_vector * mass_vector = gsl_vector_alloc(points_number);
        gsl_vector * potential_vector = gsl_vector_alloc(points_number);

        double mass_step = (mass_max - mass_min) / (points_number - 1);
        double mass = mass_min;

        double proton_density = proton_fraction * barionic_density;
        double neutron_density = (1.0 - proton_fraction) * barionic_density;

        double proton_fermi_momentum = FermiMomentum(proton_density);
        double neutron_fermi_momentum = FermiMomentum(neutron_density);

        for (int i = 0; i < points_number; i++){

            double kinectic_energy_density = KinecticEnergyDensity(mass,
                                                                   proton_fermi_momentum,
                                                                   neutron_fermi_momentum);

            double scalar_density = ScalarDensity(mass, proton_fermi_momentum, parameters.cutoff)
                                    + ScalarDensity(mass, neutron_fermi_momentum, parameter.cutoff);

            // If barionic density == 0, the chemical
            // potential functions must return zero.
            double proton_chemical_potential = ProtonChemicalPotential(proton_fermi_momentum,
                                                                       scalar_density,
                                                                       mass,
                                                                       barionic_density,
                                                                       proton_density,
                                                                       neutron_density);

            double neutron_chemical_potential = NeutronChemicalPotential(neutron_fermi_momentum,
                                                                         scalar_density,
                                                                         mass,
                                                                         barionic_density,
                                                                         proton_density,
                                                                         neutron_density);

            double kinectic_energy_density = KinecticEnergyDensity(mass,
                                                                   proton_fermi_momentum,
                                                                   neutron_fermi_momentum);

            double potential = ThermodynamicPotential(scalar_density,
                                                      barionic_density,
                                                      proton_density,
                                                      neutron_density,
                                                      proton_chemical_potential,
                                                      neutron_chemical_potential,
                                                      kinectic_energy_density);

            gsl_vector_set(mass_vector, i, mass);
            gsl_vector_set(potential_vector, i, potential);

            mass += mass_step;
        }

        WriteVectorsToFile("thermodynamic_potential_by_mass.dat",
                           "# mass (MeV), thermodynamic potential (MeV)\n",
                           2,
                           mass_vector,
                           potential_vector);
        
        fclose(log_file);
        
        UnsetFilePath();
    }
}
